"""Project-init scaffolding: gitignores, dirs, marker files, board templates.

The single source of truth for what an ap2-managed project should ignore vs.
track, and what the bare minimum on-disk skeleton looks like. Replaces the
manual transcribe-from-skill-markdown flow that left stoch's `cron.yaml`
untracked for weeks and silently accumulated `.lock` / `.bak` files.

Idempotent: re-running unions gitignores, never touches existing TASKS.md /
progress.md / CLAUDE.md content (only writes if missing or appends a new
`## Autopilot` block to a CLAUDE.md that lacks one).
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from .config import AUTOPILOT_DIR_NAME


TASKS_TEMPLATE = (
    "# Tasks\n\n"
    "## Active\n\n"
    "## Ready\n\n"
    "## Backlog\n\n"
    "## Complete\n\n"
    "## Frozen\n"
)

PROGRESS_TEMPLATE = "# Progress\n"

CLAUDE_AUTOPILOT_TEMPLATE = (
    "## Autopilot\n\n"
    "- Task list: `TASKS.md`\n"
    "- Task briefings: `.cc-autopilot/tasks/`\n"
    "- Progress log: `.cc-autopilot/progress.md`\n"
    "- Next task ID: TB-1\n"
)

# Project-level goals/non-goals anchor read by the ideation cron (TB-70). The
# template is intentionally short — humans fill it in. Empty/skeleton values
# are tolerated by the ideation prompt, which falls back to inferring goals
# from CLAUDE.md + progress.md when the file is missing or all-placeholder.
BRIEFING_TEMPLATE = (
    "# {task_id} — {title}\n\n"
    "## Goal\n\n"
    "{description}\n\n"
    "## Scope\n\n"
    "- (file / module to change)\n\n"
    "## Design\n\n"
    "(filled in by /tb prep or by the ideation agent)\n\n"
    "## Verification\n\n"
    "Concrete acceptance criteria the daemon's per-task verifier (TB-69)\n"
    "runs after the agent's commit. Shell-command bullets (backtick-fenced\n"
    "at the start of the bullet) are run automatically; prose bullets are\n"
    "judged by an SDK call against the diff.\n\n"
    "- `uv run pytest -q` — full suite passes\n"
    "- (additional shell or prose bullets)\n\n"
    "## Out of scope\n\n"
    "- (filled in)\n"
)


def render_briefing(
    *,
    task_id: str,
    title: str,
    description: str = "",
) -> str:
    """Fill `BRIEFING_TEMPLATE` for a new task. Used by `do_board_edit`'s
    `add_backlog` path when no explicit briefing payload is provided (TB-69).

    Pure formatter — no side effects, idempotent for the same inputs.
    """
    desc = description.strip() or "(one-paragraph description of what success looks like)"
    return BRIEFING_TEMPLATE.format(
        task_id=task_id,
        title=title,
        description=desc,
    )


GOAL_TEMPLATE = (
    "# Project Goals\n\n"
    "## Mission\n"
    "(one-sentence statement of what this project is FOR)\n\n"
    "## Current focus\n"
    "- (area or theme actively in flight now)\n\n"
    "## Non-goals\n"
    "- (explicit things this project is NOT trying to do, so ideation\n"
    "  doesn't propose them)\n\n"
    "## Constraints\n"
    "- (hard constraints — tech stack, deadlines, dependencies,\n"
    "  blast-radius limits)\n"
)


# Living progress assessment maintained by ideation each cycle (TB-87).
# Ideation reads the prior assessment + goal.md + Complete tail, then
# OVERWRITES this file with a fresh assessment that grounds the cycle's
# proposals in cited TB-Ns. Schema is fixed by the cron prompt — this is
# just a placeholder so first-cycle reads don't fail.
# Placeholder for `.cc-autopilot/insights/_index.md` — overwritten by
# `ap2/insights.py::regenerate_index` at the first ideation cron tick after a
# real insight file is added. Tracked in git so cloning the repo is enough to
# get a runnable scaffold (TB-89).
INSIGHTS_INDEX_PLACEHOLDER = (
    "# Insights index\n"
    "_Auto-generated by ap2 before each ideation cron tick; do not edit._\n\n"
    "(no insights yet — drop markdown files into this directory with YAML\n"
    "front matter to surface them here.)\n"
)


IDEATION_STATE_TEMPLATE = (
    "# Ideation State\n\n"
    "_Not yet generated. Will be written on the next ideation cron tick.\n"
    "Schema (set by `ap2/cron.default.yaml`'s ideation prompt):\n"
    "Mission alignment / Current focus assessment / Non-goal risk check /\n"
    "Considered & deferred / Open questions for operator / Proposals._\n"
)


# Lines that go into <project>/.cc-autopilot/.gitignore. Grouped by purpose so
# diffs against an existing file are minimal and readable.
NESTED_GITIGNORE_BLOCKS: list[tuple[str, list[str]]] = [
    ("Runtime — per-user, not committed", [
        "flag",
        "checkpoints/",
        "sessions/",
        "metrics/",
        "decisions.log",
        "context.json",
        "events.jsonl",
        "daemon.pid",
        "daemon.log",
        "paused",
        "cron_state.json",
        "mm_state.json",
        "retry_state.json",
        "auto_diagnose_state.json",
    ]),
    ("Per-run prompt + stream dumps for failure diagnosis (kept only on failure)", [
        "debug/",
    ]),
    ("Pipeline log dirs (TB-81) — local debug-only, never committed", [
        "pipelines/",
    ]),
    ("Local/sandbox-specific env (secrets, channel IDs) — keep out of git", [
        "env",
    ]),
    ("Runtime fcntl locks (cron_state.json.lock, retry_state.json.lock, etc.)", [
        "*.lock",
    ]),
    ("On-disk backups created during ap2 upgrades", [
        "*.bak",
    ]),
]

# Lines that go into the project's ROOT .gitignore (above .cc-autopilot/).
# Only entries for files ap2 creates outside .cc-autopilot/.
ROOT_GITIGNORE_BLOCKS: list[tuple[str, list[str]]] = [
    ("ap2 board lock (runtime)", [
        "TASKS.md.lock",
    ]),
]


@dataclass
class InitReport:
    project_root: Path
    nested_gitignore_added: list[str] = field(default_factory=list)
    root_gitignore_added: list[str] = field(default_factory=list)
    tasks_dir_created: bool = False
    tasks_md_created: bool = False
    progress_md_created: bool = False
    claude_md_created: bool = False
    claude_md_autopilot_added: bool = False
    goal_md_created: bool = False
    ideation_state_md_created: bool = False
    insights_dir_created: bool = False

    def print(self) -> None:
        if self.nested_gitignore_added:
            print(f"  .cc-autopilot/.gitignore: +{len(self.nested_gitignore_added)} entries")
            for line in self.nested_gitignore_added:
                print(f"    + {line}")
        else:
            print("  .cc-autopilot/.gitignore: up to date")
        if self.root_gitignore_added:
            print(f"  .gitignore: +{len(self.root_gitignore_added)} entries")
            for line in self.root_gitignore_added:
                print(f"    + {line}")
        else:
            print("  .gitignore: up to date")
        print(f"  .cc-autopilot/tasks/: {'created' if self.tasks_dir_created else 'exists'}")
        print(f"  TASKS.md: {'created' if self.tasks_md_created else 'exists'}")
        print(f"  .cc-autopilot/progress.md: {'created' if self.progress_md_created else 'exists'}")
        print(f"  goal.md: {'created (template — fill in)' if self.goal_md_created else 'exists'}")
        print(f"  .cc-autopilot/ideation_state.md: {'created (placeholder)' if self.ideation_state_md_created else 'exists'}")
        print(f"  .cc-autopilot/insights/: {'created (placeholder index)' if self.insights_dir_created else 'exists'}")
        if self.claude_md_created:
            print(f"  CLAUDE.md: created (with ## Autopilot)")
        elif self.claude_md_autopilot_added:
            print(f"  CLAUDE.md: appended ## Autopilot section")
        else:
            print(f"  CLAUDE.md: ## Autopilot section already present")


def _existing_entries(text: str) -> set[str]:
    """Pattern entries already in a gitignore (skip blank lines and comments)."""
    return {
        line.strip()
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }


def _union_gitignore(path: Path, blocks: list[tuple[str, list[str]]]) -> list[str]:
    """Append missing entries from `blocks` to `path`. Returns the lines added.

    If `path` doesn't exist, it's created and every block is written. If it
    exists, only entries not already present (by exact-string match) are
    appended, each grouped under its header. Headers are written only when the
    block contributes at least one new entry, so re-runs don't accumulate
    empty header sections.
    """
    text = path.read_text() if path.exists() else ""
    existing = _existing_entries(text)
    added: list[str] = []
    chunks: list[str] = []
    for header, entries in blocks:
        new_entries = [e for e in entries if e not in existing]
        if not new_entries:
            continue
        chunks.append(f"\n# {header}\n" + "\n".join(new_entries) + "\n")
        added.extend(new_entries)
        existing.update(new_entries)  # protect against intra-block dups

    if not added:
        return []

    path.parent.mkdir(parents=True, exist_ok=True)
    if text and not text.endswith("\n"):
        text += "\n"
    path.write_text(text + "".join(chunks))
    return added


# Word-boundary + any-trailing-content match (TB-102): tolerates
# `## Autopilot (per-project)` etc. while still rejecting look-alikes
# like `## AutopilotPlus`.
_AUTOPILOT_HEADER_RE = re.compile(r"^##\s+Autopilot\b[^\n]*$", re.M)


def _ensure_file(path: Path, content: str) -> bool:
    """Write `content` to `path` only if `path` does not already exist."""
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def _ensure_claude_md_autopilot(claude_md: Path) -> tuple[bool, bool]:
    """Ensure CLAUDE.md exists and has a `## Autopilot` section.

    Returns `(claude_md_created, autopilot_appended)`:
    - `(True, False)` — CLAUDE.md was missing; created with header + Autopilot.
    - `(False, True)` — CLAUDE.md existed without Autopilot; we appended.
    - `(False, False)` — Autopilot section already present; nothing changed.
    """
    if not claude_md.exists():
        claude_md.parent.mkdir(parents=True, exist_ok=True)
        claude_md.write_text("# CLAUDE.md\n\n" + CLAUDE_AUTOPILOT_TEMPLATE)
        return True, False
    text = claude_md.read_text()
    if _AUTOPILOT_HEADER_RE.search(text):
        return False, False
    sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    claude_md.write_text(text + sep + CLAUDE_AUTOPILOT_TEMPLATE)
    return False, True


def init_project(project_root: Path) -> InitReport:
    """Scaffold ap2 gitignores, tasks dir, board template, autopilot config.

    Idempotent — every step skips if the target already exists. Never clobbers
    user content; CLAUDE.md only gains a fresh `## Autopilot` block when the
    file lacks one entirely.
    """
    project_root = project_root.resolve()
    autopilot_dir = project_root / AUTOPILOT_DIR_NAME

    nested_added = _union_gitignore(autopilot_dir / ".gitignore", NESTED_GITIGNORE_BLOCKS)
    root_added = _union_gitignore(project_root / ".gitignore", ROOT_GITIGNORE_BLOCKS)

    tasks_dir = autopilot_dir / "tasks"
    tasks_dir_created = not tasks_dir.exists()
    tasks_dir.mkdir(parents=True, exist_ok=True)

    # TB-89: insights directory + placeholder index. Lazy regen kicks in
    # the first time a cron tick fires after a real insight file lands.
    insights_dir = autopilot_dir / "insights"
    insights_dir_created = not insights_dir.exists()
    insights_dir.mkdir(parents=True, exist_ok=True)
    _ensure_file(insights_dir / "_index.md", INSIGHTS_INDEX_PLACEHOLDER)

    tasks_md_created = _ensure_file(project_root / "TASKS.md", TASKS_TEMPLATE)
    progress_md_created = _ensure_file(autopilot_dir / "progress.md", PROGRESS_TEMPLATE)
    goal_md_created = _ensure_file(project_root / "goal.md", GOAL_TEMPLATE)
    ideation_state_md_created = _ensure_file(
        autopilot_dir / "ideation_state.md", IDEATION_STATE_TEMPLATE,
    )
    claude_md_created, autopilot_added = _ensure_claude_md_autopilot(project_root / "CLAUDE.md")

    return InitReport(
        project_root=project_root,
        nested_gitignore_added=nested_added,
        root_gitignore_added=root_added,
        tasks_dir_created=tasks_dir_created,
        tasks_md_created=tasks_md_created,
        progress_md_created=progress_md_created,
        claude_md_created=claude_md_created,
        claude_md_autopilot_added=autopilot_added,
        goal_md_created=goal_md_created,
        ideation_state_md_created=ideation_state_md_created,
        insights_dir_created=insights_dir_created,
    )
