"""Project-output insights directory + auto-regenerated index (TB-89).

`.cc-autopilot/insights/` holds markdown files with YAML front matter
describing what the project has *learned* — metric thresholds, calibration
findings, evaluation results, decisions. Ideation reads `_index.md` (a one-
line-per-insight summary, regenerated by ap2 when files change) before
proposing tasks, so its rankings are grounded in real project signal.

Convention, not framework:
- Anyone (operator, task agents, ideation-proposed `#evaluation` tasks) can
  write a markdown file to this directory.
- Required YAML front matter at top of each file: `tldr` (one-line
  summary), `updated` (RFC3339 UTC), `updated_by` (TB-N or `operator`),
  `cites` (list of TB-Ns).
- ap2 walks the dir, parses front matter, and writes `_index.md` ordered by
  `updated` desc.

Lazy regen: in steady state the helper is N `stat()` calls and a single
mtime comparison. Only does I/O when a file's mtime exceeds the index's,
or when the directory's mtime advances (file added/removed).
"""
from __future__ import annotations

import datetime as dt
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .config import AUTOPILOT_DIR_NAME, Config

INSIGHTS_DIR_NAME = "insights"
INDEX_FILE_NAME = "_index.md"

_INDEX_HEADER = (
    "# Insights index\n"
    "_Auto-generated by ap2 before each ideation cron tick; do not edit._\n\n"
)

_PLACEHOLDER_INDEX = (
    _INDEX_HEADER
    + "(no insights yet — drop markdown files into this directory with YAML\n"
    + "front matter to surface them here.)\n"
)


@dataclass
class InsightSummary:
    """Parsed front matter + filename for one insight file."""

    filename: str
    tldr: str
    updated: str  # RFC3339 UTC; sortable as a string for desc ordering
    updated_by: str
    cites: list[str]

    def to_index_line(self) -> str:
        cite_str = "/".join(self.cites) if self.cites else "—"
        # Strip the trailing `T...Z` so the index line is readable.
        date_only = self.updated.split("T")[0] if self.updated else "?"
        return (
            f"- `{self.filename}` — {self.tldr} "
            f"({self.updated_by}, {date_only}, cites {cite_str})"
        )


def insights_dir(cfg: Config) -> Path:
    return cfg.project_root / AUTOPILOT_DIR_NAME / INSIGHTS_DIR_NAME


def index_path(cfg: Config) -> Path:
    return insights_dir(cfg) / INDEX_FILE_NAME


def _list_insight_files(insights: Path) -> list[Path]:
    if not insights.exists():
        return []
    return sorted(
        f for f in insights.iterdir()
        if f.is_file() and f.suffix == ".md" and f.name != INDEX_FILE_NAME
    )


def _parse_front_matter(text: str) -> dict:
    """Best-effort YAML front matter parser.

    Looks for a `---`-fenced block at the top of the file. Returns a dict
    with keys `tldr`, `updated`, `updated_by`, `cites`. Missing/malformed
    front matter returns an empty dict; callers fall back to "(no tldr —
    needs update)" rather than raising.

    We don't import yaml here to keep the helper free of optional deps —
    the front matter is line-oriented enough that a small parser handles
    the cases we care about.
    """
    if not text.startswith("---"):
        return {}
    rest = text[3:]
    end = rest.find("\n---")
    if end < 0:
        return {}
    block = rest[:end].strip("\n")
    out: dict = {}
    for raw_line in block.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            out[key] = [
                tok.strip().strip('"').strip("'") for tok in inner.split(",")
                if tok.strip()
            ]
        else:
            out[key] = val.strip('"').strip("'")
    return out


def _summarize_file(path: Path) -> InsightSummary:
    """Build an `InsightSummary` from a single insight file."""
    try:
        text = path.read_text()
    except OSError:
        text = ""
    fm = _parse_front_matter(text)
    cites = fm.get("cites", [])
    if isinstance(cites, str):
        cites = [c.strip() for c in cites.split(",") if c.strip()]
    return InsightSummary(
        filename=path.name,
        tldr=str(fm.get("tldr") or "(no tldr — needs update)"),
        updated=str(fm.get("updated") or ""),
        updated_by=str(fm.get("updated_by") or "?"),
        cites=list(cites) if isinstance(cites, list) else [],
    )


def _render_index(summaries: Iterable[InsightSummary]) -> str:
    summaries = sorted(
        summaries, key=lambda s: s.updated or "", reverse=True,
    )
    if not summaries:
        return _PLACEHOLDER_INDEX
    lines = [_INDEX_HEADER.rstrip(), ""]
    for s in summaries:
        lines.append(s.to_index_line())
    return "\n".join(lines) + "\n"


def regenerate_index(cfg: Config) -> bool:
    """Force a regen. Returns True if the index was written."""
    insights = insights_dir(cfg)
    if not insights.exists():
        return False
    files = _list_insight_files(insights)
    summaries = [_summarize_file(f) for f in files]
    rendered = _render_index(summaries)
    index = index_path(cfg)
    # Write atomically: tmpfile + rename. Avoids a partial index racing with
    # an ideation read.
    tmp = index.with_suffix(".md.tmp")
    tmp.write_text(rendered)
    tmp.replace(index)
    return True


def maybe_regenerate_index(cfg: Config) -> bool:
    """Lazy regen — no-op when nothing changed since the index's last write.

    Compares the index file's mtime against the directory's mtime (which
    bumps on file add/remove on Unix) and against each insight file's mtime.
    Returns True iff a regeneration actually happened.

    Steady-state cost is N `stat()` calls plus a couple of comparisons —
    effectively free when the dir is quiet.
    """
    insights = insights_dir(cfg)
    if not insights.exists():
        return False
    files = _list_insight_files(insights)
    index = index_path(cfg)
    if not index.exists():
        regenerate_index(cfg)
        return True
    try:
        index_mtime = index.stat().st_mtime
        dir_mtime = insights.stat().st_mtime
    except OSError:
        regenerate_index(cfg)
        return True
    if dir_mtime > index_mtime:
        regenerate_index(cfg)
        return True
    if any(f.stat().st_mtime > index_mtime for f in files):
        regenerate_index(cfg)
        return True
    return False
